parameters:
- name: runAutomationTests #will let us toggle automation tests on or off
  type: boolean
  default: true

   
stages:
  - stage: DeployToDev4Regulators
    jobs:
      - job: DeployToDev4Regulators
        displayName: DeployToDev4 (Regulators)
        condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
        steps:
          - template: templates/deployment.yaml@CommonTemplates
            parameters:
              imageTag: 'main-latest'
              azureSubscription: 'AZD-RWD-DEV4'
              acrName: 'devrwdinfac1401'
              registryName: 'facadeaccountcreationrepository'
              serviceName: 'devrwdwebwa4413'
              targetEnvironment: 'development'

      - ${{ if eq(parameters.runAutomationTests, true) }}:
        - job: RunAutomationTest
          displayName: DEV4 Automation Testing
          dependsOn: DeployToDev4Regulators
          steps:
            - checkout: AutomationTesting
            - template: automation-testing-regulators.yaml@AutomationTesting
              parameters:
                env: 'dev4'
